# Generated by Django 3.1.2 on 2020-10-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_reliefcamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutngo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('ngoname', models.CharField(max_length=122)),
                ('desc', models.TextField()),
            ],
        ),
    ]
