# Generated by Django 3.1.2 on 2020-10-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_data1_data2_data3_data4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('Rivername', models.CharField(max_length=122)),
                ('desc', models.TextField()),
                ('year', models.IntegerField()),
            ],
        ),
    ]
